### PR TITLE
Add support for --ssl and --authenticationDatabase options

### PR DESCRIPTION
**Pull request by joeyAghion**
This is an attempt to support `--ssl` and `--authenticationDatabase` options for mongo shell operations. It builds on the work from [artsy/mongoid-shell/tree/fea-ssl-authDatabase](https://github.com/artsy/mongoid-shell/tree/fea-ssl-authDatabase), but there have been significant refactors on the trunk mongoid/mongoid-shell repo, so that work isn't cleanly mergeable.

This also changes the implementation to respect `session.options` by default, so callers who provide a session don't also need to supply the `ssl` and `authenticationDatabase` options.

### CODE REVIEW

**Comment by cavvia** [comment]
This looks good to me, and simplifies things considerably for the client code.

**Comment by cavvia** [comment]
I'm going to merge in and attempt to rebase upstream.

**Comment by cavvia** [comment]
Rebased and PR'd here: https://github.com/mongoid/mongoid-shell/pull/16

**Comment by dblock** [comment]
This repo is a fork of a fork, maybe we should ✂️ it?

**Pull request merged**
